spring.jpa:
  database: POSTGRESQL
  hibernate.ddl-auto: update
  show-sql: true

spring.datasource:
  platform: postgres
  driverClassName: org.postgresql.Driver
  url: jdbc:postgresql://${DB_IP:localhost}:5432/awilix
  username: postgres
  password: ${DB_PASSWORD:123456}
 
logging:
  level:
    org.hibernate.engine.jdbc.env.internal.LobCreatorBuilderImpl: ERROR
  path:
    ${LOG_LOCATION:./}

spring.mail:
  host: email-smtp.us-west-2.amazonaws.com
  username: username
  password: password
  protocol: smtp
  properties:
    port: 25
    auth: true
    starttls.enable: true
    starttls.required: true

spring.sendgrid.api-key: ${SENDGRID_KEY}